name: Publish Docker image

on:
  workflow_dispatch:
  push:

jobs:

  build:
    name: build coredns binary
    runs-on: ubuntu-latest
    env:
      GOOS: linux
      GOARCH: amd64

    steps:

      - uses: actions/checkout@v3
        with:
          path: ./tmp/build

      - run: echo "COREDNS_VERSION=$(yq '.coredns' version.yml)" >> $GITHUB_ENV
        working-directory: ./tmp/build

      - uses: actions/checkout@v3
        with:
          repository: coredns/coredns
          ref: ${{ env.COREDNS_VERSION }}

      - run: |
          cp ./tmp/build/plugin.cfg .
          rm -rf ./tmp/build

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/coredns:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/coredns:${{ env.COREDNS_VERSION }}