name: Publish Docker image

on:
  workflow_dispatch:
  push:

jobs:

  build:
    name: build coredns binary
    runs-on: ubuntu-latest
    env:
      GOOS: linux
      GOARCH: amd64

    steps:

      - uses: actions/checkout@v3

      - run: echo "COREDNS_VERSION=$(yq '.coredns' version.yaml)" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          repository: coredns/coredns
          path: coredns
          ref: ${{ env.COREDNS_VERSION }}

      - run: echo "GO_VERSION=$(go mod edit -json | jq -r .Go)" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          path: build

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - run: cat plugin.cfg >> build/plugin.cfg

      - run : |
          make
          chmod +x coredns
          cp coredns ../
        working-directory: ./build

      - run: rm -rf build


      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/coredns:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/coredns:${{ env.COREDNS_VERSION }}