name: Publish Docker image

on:
  workflow_dispatch:
  push:

jobs:

  build:
    name: build coredns binary
    runs-on: ubuntu-latest
    env:
      GOOS: linux
      GOARCH: amd64

    steps:

      - uses: actions/checkout@v3

      - run: echo "COREDNS_VERSION=$(yq '.coredns' version.yml)" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          repository: coredns/coredns
          path: build
          ref: ${{ env.COREDNS_VERSION }}

      - run: echo "GO_VERSION=$(go mod edit -json | jq -r .Go)" >> $GITHUB_ENV
        working-directory: ./build

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - run: |
          rm ./build/plugin.cfg
          mv plugin.cfg ./build/plugin.cfg

      - run : |
          make coredns
          chmod +x coredns
          cp coredns ../
        working-directory: ./build

      - run: |
          ls
          rm -rf build


      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/coredns:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/coredns:${{ env.COREDNS_VERSION }}