name: Publish Docker image

on:
  push:

jobs:

  # build coredns binary with a single arch
  build:
    name: build coredns binary
    runs-on: ubuntu-latest
    env:
      GOOS: linux
      GOARCH: amd64
    steps:
      - run: |
          echo "COREDNS_VERSION=$(curl -s https://api.github.com/repos/coredns/coredns/releases/latest | jq '.tag_name' | sed 's/\"//g')" >> "$GITHUB_ENV"
      - uses: actions/checkout@v3
        with:
          repository: coredns/coredns
          ref: ${{ env.COREDNS_VERSION }}
          path: coredns
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'coredns/go.mod'
      - uses: actions/checkout@v3
        with:
          path: config
      - run: |
          cp config/plugin.cfg coredns/
      - run: sudo apt install libunbound-dev -y
      - run: make
        working-directory: coredns
        env:
          CGO_ENABLED: 1
      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            coredns/coredns
          if-no-files-found: error
  # build and deploy docker image
  docker:
    name: build docker image
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - run: ls

      # - uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # - uses: docker/build-push-action@v4
      #   with:
      #     context: coredns/.
      #     push: true
      #     tags: |
      #       ${{ secrets.DOCKER_HUB_USERNAME }}/coredns:latest
      #       ${{ secrets.DOCKER_HUB_USERNAME }}/coredns:${{ env.COREDNS_VERSION }}