name: Publish Docker image

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  # build coredns binary with a single arch
  build:
    name: build coredns binary
    runs-on: ubuntu-latest
    env:
      GOOS: linux
      GOARCH: amd64
    outputs:
      COREDNS_VERSION: ${{ steps.version.outputs.COREDNS_VERSION }}
    steps:
      - id: version
        run: |
          echo "COREDNS_VERSION=$(curl -s https://api.github.com/repos/coredns/coredns/releases/latest | jq '.tag_name' | sed 's/\"//g')" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v3
        with:
          repository: coredns/coredns
          ref: ${{ steps.version.outputs.COREDNS_VERSION }}
          path: coredns
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'coredns/go.mod'
      - uses: actions/checkout@v3
        with:
          path: config
      - run: |
          cp config/plugin.cfg coredns/
      - run: |
          sudo apt-get -qq update && \
          sudo apt-get -yyqq install libunbound-dev -y \
        env:
          DEBCONF_NONINTERACTIVE_SEEN: true
          DEBIAN_FRONTEND: noninteractive
          DEBIAN_PRIORITY: critical
          TERM: linux
      - run: make
        working-directory: coredns
        env:
          CGO_ENABLED: 1
      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            coredns/coredns
          if-no-files-found: error
  # build and deploy docker image
  docker:
    name: build docker image
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: docker/metadata-action@v4
        id: metadata
        with:
          images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/coredns
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}},value=${{ needs.build.outputs.COREDNS_VERSION }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}