name: Publish Docker image

on:
  workflow_dispatch:
  push:

jobs:

  gitversion:
    name: Determine the intended website version
    runs-on: ubuntu-latest
    outputs:
      majorminorpatch: ${{ steps.gitversion.outputs.majorMinorPatch }}
      semver: ${{ steps.gitversion.outputs.semVer }}
      shortsha: ${{ steps.gitversion.outputs.shortSha }}
      branchname: ${{ steps.gitversion.outputs.branchName }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7

  build:
    name: Build for linux_amd64
    runs-on: ubuntu-latest
    env:
      SEMVER: ${{ needs.gitversion.outputs.semver }}
      SHORTSHA: ${{ needs.gitversion.outputs.shortsha }}
      MAJORMINORPATCH: ${{ needs.gitversion.outputs.majorminorpatch }}
      BRANCH: ${{ needs.gitversion.outputs.branchname }}
    needs:
      - gitversion
    steps:
      - uses: actions/checkout@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ganawa
          password: ${{ secrets.GHP_TOKEN }}

      - name: Build and push non-main docker image
        if: contains(env.BRANCH, 'develop') || startsWith(env.BRANCH, 'release') || startsWith(env.BRANCH, 'hotfix') || startsWith(env.BRANCH, 'tags')
        run: |
          docker build . \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/coredns-builder:${{ env.SEMVER }} \
            -t ghcr.io/${{ github.repository_owner }}/coredns-builder:${{ env.SEMVER }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/coredns-builder:${{ env.SEMVER }}
          docker push ghcr.io/${{ github.repository_owner }}/coredns-builder:${{ env.SEMVER }}

      - name: Build and push main/latest docker image
        if: contains(env.BRANCH, 'main')
        run: |
          docker build . \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/coredns-builder:latest \
            -t ghcr.io/${{ github.repository_owner }}/coredns-builder:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/coredns-builder:latest
          docker push ghcr.io/${{ github.repository_owner }}/coredns-builder:latest

      - name: Build and push non-tagged docker image
        if: "!startsWith(env.BRANCH, 'develop') && !startsWith(env.BRANCH, 'release') && !startsWith(env.BRANCH, 'hotfix') && !startsWith(env.branchName, 'main') && !startsWith(env.BRANCH, 'tags')"
        run: |
          docker build . \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/coredns-builder:${{ env.SHORTSHA }} \
            -t ghcr.io/${{ github.repository_owner }}/coredns-builder:${{ env.SHORTSHA }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/coredns-builder:${{ env.SHORTSHA }}
          docker push ghcr.io/${{ github.repository_owner }}/coredns-builder:${{ env.SHORTSHA }}

      - uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ganawa
          slug: ganawa/coredns-builder
          pass: ${{ secrets.DOCKER_HUB_PASS }}
          description: true